### ISSUE TITLE
different interpolation logic

### ISSUE THREAD

**Issue by fzhang612** [ShenYujun/InterFaceGAN#1]
Hi,

First many thanks for sharing this great work.

Got a question regarding the linear interpolation logic. In function `linear_interpolate()`, when `len(latent_code.shape) == 2`, dot product of `latent_code` and `boundary` is subtracted from `[start_distance, end_distance]`. However if `if len(latent_code.shape) == 3`,  the dot product is not considered at all. Just wondering why these 2 cases are treated differently.

Thanks.

**Comment by ShenYujun** [comment]
Good point. That is because when `len(latent_code.shape) == 3`, it means the latent code comes from the W+ space of StyleGAN. Taking model with 1024 resolution as an example, W+ space consists of disentangled latent codes `w` fed into all 18 convolutional layers. Normally, all these 18 vectors are exactly the same. However, they can be different actually (i.e., they have different distances to the given `boundary`). In such case, it is very hard to decide using which one to compute the dot product (NOTE: We can not subtract the dot product from these latent codes independently, since that will change the original synthesis. Or say, all latent codes should have same behavior.). Accordingly, when using W+ space, we choose to not deal with the dot product.

**Comment by fzhang612** [comment]
Thanks for your response.

I think I understand why not to subtract the dot product independently in the `W+` space. However have you considered subtracting the average of the 18 dot products (one dot product per layer), or the min/max of them?

**Comment by ShenYujun** [comment]
Subtracting average/min/max of the 18 dot products is indeed one option, but it is hard to tell which strategy is better (Unfortunately, we don't have rigorous evaluation from this aspect). The key idea of subtracting the dot product for `len(latent_code.shape) == 2` case is to better control the distance between sampled latent code and the target semantic boundary. Client can always use larger `start_distance` and `end_distance` to get more manipulation results. From this viewpoint, this logic does not matter that much.
