### ISSUE TITLE
Ways of learning the attribute vector

### ISSUE THREAD

**Issue by xunhuang1995** [ShenYujun/InterFaceGAN#5]
Very impressive work! I'm wondering if you have compared the proposed way of learning the attribute vector (by classification) with the way in [1] (by simply using the difference between the mean features)?. 

[1] P. Upchurch, J. Gardner, G. Pleiss, R. Pless, N. Snavely, K. Bala, and K. Weinberger. Deep feature interpolation for image content changes. In CVPR, 2017

**Comment by ShenYujun** [comment]
Thanks. We do not compare with that work. (We guess that training a classifier is more stable than just using mean features since more data is used for searching the boundary. But you are right, an comparison experiment is needed to support this claim. If you are interested, you can replace the `train_boundary` functon in `utils/manipulator.py`.) Actually, using SVM for classification is just one solution to boundary search. Clients can use whatever method they like to achieve this goal, and this repo just provides one feasible way. The main contribution is that we found that unconditional GAN actually learns to encode semantics into the latent space. Some semantics may correlate with each other, but the proposed conditional manipuation method can help reveal such disentanglement.

**Comment by xunhuang1995** [comment]
Thank you for the quick response. I'll try it out when I have time :). Again, nice work!
